#!/bin/bash

# Local Settings - season to taste
readonly DIGITEMP_CMD=digitemp_DS9097U         # actual digitemp command to run
readonly SENSOR_ID=0                           # sensor ID from the config file
readonly DIGITEMP_CONF=/root/.digitemp.conf    # digitemp config file
readonly DIGITEMP_DEVICE=/dev/ttyUSB0          # where the sensor is attached

exists()
{
  command -v "$1" >/dev/null 2>&1
}
# Check for programs
if ! exists bc ; then
  echo "ERR: bc not installed"
  exit 3
fi
if ! exists $DIGITEMP_CMD ; then
  echo "ERR: $DIGITEMP_CMD not installed"
  exit 3
fi
if ! [ -f $DIGITEMP_CONF ] ; then
  echo "ERR: $DIGITEMP_CONF not found"
  exit 3
fi
#if ! [ -f $DIGITEMP_DEVICE ] ; then
#  echo "ERR: $DIGITEMP_DEVICE not found"
#  exit 3
#fi

readonly TEMP=$($DIGITEMP_CMD -t $SENSOR_ID -q -s $DIGITEMP_DEVICE -c $DIGITEMP_CONF -o "%.2F")
if [ "Z" == "Z$TEMP" ] ; then
  echo "ERR: Error running $DIGITEMP_CMD, no temperature returned"
  exit 3
fi

readonly MAX_WARN=75
readonly MAX_CRIT=80
readonly MIN_WARN=60
readonly MIN_CRIT=55

MESSAGE="Current Temp: $TEMP"

if [ $(echo "$TEMP > $MAX_CRIT" | bc) -eq 1 ] ; then
  echo "CRIT: $MESSAGE"
  exit 2
fi
if [ $(echo "$TEMP > $MAX_WARN" | bc) -eq 1 ] ; then
  echo "WARN: $MESSAGE"
  exit 1
fi
if [ $(echo "$TEMP < $MIN_CRIT" | bc) -eq 1 ] ; then
  echo "CRIT: $MESSAGE"
  exit 2
fi
if [ $(echo "$TEMP < $MIN_WARN" | bc) -eq 1 ] ; then
  echo "WARN: $MESSAGE"
  exit 1
fi
echo "OK: $MESSAGE"
exit 0

