#!/bin/bash

# Local Settings - season to taste
readonly DIGITEMP_CMD=digitemp_DS9097U         # actual digitemp command to run
readonly SENSOR_ID=0                           # sensor ID from the config file
readonly DIGITEMP_CONF=/root/.digitemp.conf    # digitemp config file
readonly DIGITEMP_DEVICE=/dev/ttyUSB0          # where the sensor is attached

exists()
{
  command -v "$1" >/dev/null 2>&1
}
# Check for programs
if ! exists bc ; then
  echo "ERR: bc not installed"
  exit 3
fi
if ! exists $DIGITEMP_CMD ; then
  echo "ERR: $DIGITEMP_CMD not installed"
  exit 3
fi
if ! [ -f $DIGITEMP_CONF ] ; then
  echo "ERR: $DIGITEMP_CONF not found"
  exit 3
fi
#if ! [ -f $DIGITEMP_DEVICE ] ; then
#  echo "ERR: $DIGITEMP_DEVICE not found"
#  exit 3
#fi

readonly TEMP=$($DIGITEMP_CMD -t $SENSOR_ID -q -s $DIGITEMP_DEVICE -c $DIGITEMP_CONF -o "%.2F")
if [ "Z" == "Z$TEMP" ] ; then
  echo "ERR: Error running $DIGITEMP_CMD, no temperature returned"
  exit 3
fi

readonly WARNING=75
readonly CRITICAL=80

MESSAGE="Current Temp: $TEMP"
PERF_DATA="temp=$TEMP,$WARNING,$CRITICAL"

if [ $(echo "$TEMP > $CRITICAL" | bc) -eq 1 ] ; then
  echo "CRIT: $MESSAGE | $PERF_DATA"
  exit 2
fi
if [ $(echo "$TEMP > $WARNING" | bc) -eq 1 ] ; then
  echo "WARN: $MESSAGE | $PERF_DATA"
  exit 1
fi
echo "OK: $MESSAGE | $PERF_DATA"
exit 0

